dmrec:
  - regex: ^$
    which: all
file:
  - method: check_filenames_assets
    args: ['file']
    # no which on method!
subject: ~ # to do
creator:
  - method: 
    args: 
# need to do a method for each creator type? ex. photographer vs author vs artist etc. or just do creator?
genus: ~
species: ~
# many more: # to do
# geonames add ending with /?