dmrec:
  - regex: ^$
    which: all
file:
  - method: check_filenames_assets
    args: ['file']
    # no which on method!
subject: ~ # to do
creator:
  - regex: '^.+$'
    which: all
  - method: validate_controlled_vocab
    args: ['creator']

species: ~
# many more: # to do
# geonames add ending with /?